stages:
  - build
  - test

image: node

build:
  stage: build
  script:
    - npm run build

test:lint:
  stage: test
  script:
    - npm run lint-check
 
test:unit:
  stage: test
  script:
    - npm run test