stages:
  - build
  - test

image: node

build:
  stage: build
  script:
    - npm i
    - npm run build

test:lint:
  dependencies:
    - build
  stage: test
  script:
    - npm i
    - npm run lint-check
 
test:unit:
  dependencies:
    - build
  stage: test
  script:
    - npm i
    - npm run ci-test